### PR TITLE
111 organizer notifications bug

### LINKED ISSUE #111: Organizer Notifications doesn't work
When going to the organizer notification dashboard all the fields are greyed out

### PR DESCRIPTION
**Pull request by Orion-W**
Finally got the past notifications showing

### CODE REVIEW

File: app/src/main/java/com/example/impact/view/OrganizerNotificationsFragment.java [hunk 1]
```diff
@@ -63,6 +75,51 @@ public static OrganizerNotificationsFragment newInstance(String organizerId) {
...
+                },
+                // error -> Toast.makeText(requireContext(), "Unable to load notifications :"+error.toString(), Toast.LENGTH_SHORT).show());
+                error -> {throw new RuntimeException(error);});
+    }
+    /**
+     * Updates the adapter when Firestore returns results.
+     */
+    private void onNotificationsLoaded(List<Notification> notifications) {
+        if (notifications.isEmpty()) {
+            Toast.makeText(requireContext(), "Orion there are no notificaoison ", Toast.LENGTH_SHORT).show();
```
Comment (jeremycarefoot) [inline app/src/main/java/com/example/impact/view/OrganizerNotificationsFragment.java]: I don't think we should be telling every user of our app "Orion there are no notificaoison" haha

File: app/src/main/java/com/example/impact/view/OrganizerNotificationsFragment.java [hunk 2]
```diff
@@ -27,32 +30,41 @@
...
 
     private Spinner sEventSelect;
     private RadioGroup radioGroup;
     private RadioButton rbWinners, rbWaitingList, rbCancelled;
     private EditText etMessage;
     private Button btnSend;
+    private TextView emptyStateView;
     private Event selectedEvent;
+
+    private List<Pair<User, WaitingListEntry>> globalWaitingListPairs;
```
Comment (jeremycarefoot) [inline app/src/main/java/com/example/impact/view/OrganizerNotificationsFragment.java:56]: Nothing that needs fixing here, but next time you need a "list of pairs" type data structure in Java you should check out HashMap. It may or may not work here but is typically better practice (faster, less memory).
